

# Should throw an exception.

sub main
  if false
    x=4
  end
  print(x)
end

main()

